#! /bin/sh

# Example bwmrc configuration
# This file is executed at server startup

# Set up desktops (names separated by spaces)
bmsg monitor -d I II III IV V VI VII VIII IX X

bmsg output eDP-1 scale 1.5

# Set border width
bmsg config border_width 5

# Set window gap
bmsg config window_gap 0

# Set single monocle
bmsg config single_monocle true

# Set borderless monocle
bmsg config borderless_monocle true

# Set gapless monocle
bmsg config gapless_monocle true

# Input config
bmsg input type:keyboard xkb_layout de
bmsg input type:touchpad natural_scroll true
bmsg input type:touchpad tap true

# Rules
bmsg rule -a com.dec05eba.gpu_screen_recorder state=floating center=on

# Start apps
swaybg -i ~/Pictures/Backgrounds/bg.png &
/home/dylan/Repos/Waybar/build/waybar &
swayidle -w timeout 120 'chayang && swaylock -f -c 000000' &
